apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agents.ai.specs
spec:
  group: ai.specs
  names:
    kind: Agent
    plural: agents
  scope: Namespaced
  versions:
    - name: v1alpha7
      served: true
      storage: true
