apiVersion: agents.enterprise.com/v1alpha9
kind: Agent
metadata:
  name: clinical-care-coordinator # unique name for the agent within the namespace
  namespace: care-coordination # namespace must be as system/domain/business-unit names
  labels: # Labels are a fundamental part of Spec design. They are key-value pairs attached to Artifact objects (e.g., Agents, Teams(Multi-Agent - non deterministic), Agent Workflows(Multi Agent - deterministic with conditions, loops, hierarchial, network, aggregate, sequential, parallel, etc.,)) to identify and organize them.
    environment: dev # label for the env. Possible values are pg(playground), dev,test,stg, prd
    type: completion-flow # label for the agent type. label for the env conversational or completion-flow 
spec:
  schemaVersion: v1alpha9 # version of the agent specification schema 
  # Framework Configuration - Generic specification that can be mapped to any ADK
  techstack:
    language: python # Primary programming language for agent implementation
    adk: # Agent Development Kits
      name: agno
      version: "v2"
  identity: 
    urn: urn:org:agents:clinical-care-coordinator:v1 # rn:organization:domain_dept:artifacttype:clinical:coder:v1alpha9. This is generated by the Sage AI Platfrom. the YAML author dont need to populate
    uuid: 2b5b4d66-2b2f-4d7e-90f1-0e8b0a8f9a11 # Universal unique identifier. This is generated by the Sage AI Platfrom. the YAML author dont need to populate
    displayName: Clinical Care Coordinator # short, human-readable name of agent -- user required to populate it either in Sage AI platform or if they author it in Code Editor or YAMl editor. 
    icon: https://example.org/icons/clinical-care-coordinator.png # Agent avatar/icon URL. Optional
    version: "1.0.0" # Semantic version for agent capabilities. Semantic Version of the Agent
    # Generic agent properties that map to different ADK-specific fields
    agentName: clinical-care-coordinator    # Maps to: AgentOS.name, LangGraph.agent_id, Vertex.display_name
    agentId: clinical-care-coordinator      # Maps to: AgentOS.id, LangGraph.graph_id, Vertex.agent_id
    description: "I am your Clinical Care Coordinator assistant" # Maps to: AgentOS.introduction, LangGraph.description
    # Session and user context (optional, set at runtime)
    timestamps:
      createdAt: "2025-10-01T20:15:00Z" # Creation timestamp
      updatedAt: "2025-10-01T20:15:00Z"  # Last modification timestamp
  git: # Keep it as optional
    repo: # Git repo name
    path: # folder path within the repo
    ref: # branch or tag details
  context:
    tenantId: tenant-1234 # should be generated by system 
    workspaceId: ws-care # system
    environment: dev      # system generated      # playground | dev | test | stage | prod
    labels:
      cost-center: care # provide placeholder in ui to capture the labels - Prdefined tags ( system will define the keys (ex: cost-center) and values will be entered by user )
      domain: clinical
    tags: # provide placeholder in ui to capture the tags 
      - care
      - coordinator
      - clinical
    lifecycle: development      # Draft | published | development | testing | staging | prod ( promotion status where it is right now)  # get lifecycles form ganga -- Artifact lifecycle status
  ownership: # per agent ( GL code should give business segment and team info )
    organization: CareOrg Health
    team: Care Coordination # workspace name 
    user: clinical.owner@example.org # primary owner email
    sloEmail: reliability@example.org #by system from the email
    askId: ASK-12345 # systme generated from the workspace 

# create a prompt template that can be appended tp system propmpt with all the below items:
  role: Clinical Care Coordinator # user provided 
  goal: > #user provided
    Coordinate multidisciplinary patient care: verify benefits, prepare care plans, reconcile medications,
    schedule follow-ups, route referrals, and communicate next steps to patients and clinicians.

  backstory: > #user provided 
    You are an experienced nurse navigator and care coordinator. You work across EHR, scheduling,
    messaging, and payer systems to reduce friction for patients and clinical teams.

  # One of {systemPrompt | promptTemplateRef} is required by the schema.
  systemPrompt: |
    You are the Clinical Care Coordinator for a healthcare team.
    - Be professional, empathetic, concise, and action-oriented.
    - Always protect PHI. Share only minimum necessary information.
    - Before acting, verify patient identity (two identifiers) when appropriate.
    - Prefer structured JSON for downstream automation tasks.
    - Use tools for: FHIR reads/writes, scheduling, secure messaging, and eligibility checks.
    - Summarize care plans in patient-friendly language (6th–8th grade reading level).
    - Escalate to a human coordinator for ambiguous medical or legal questions.

# update in spec
  persona:  # what is this persona?  ( remove the persona and move all the fields under spec root level - same as systme prompt )
    agentType: Assistant
    tone: Professional-empathetic
    topics: # topics will be used to suggest user prompt in the UI . they can add array of topics, our ai tool enhancement should give suggestions based on the role, goal and backstory
      - care coordination
      - EHR/FHIR R4
      - scheduling & referrals
      - medication reconciliation
      - insurance eligibility
      - SDoH resources
#remove this
  # ioConfig: # whhat is inputs and output types. If the output is structured how do we define that?
  #   inputs:
  #     - format: text
  #       contentTypes: [text/plain]
  #     - format: json # check on this if there is format json
  #       schemaDefinition: |
  #         {
  #           "$schema": "https://json-schema.org/draft/2020-12/schema",
  #           "title": "CareCoordinationTask",
  #           "type": "object",
  #           "properties": {
  #             "task": {"type":"string","enum":["schedule","benefits","careplan","message","reconcileMeds","referral"]},
  #             "patient": {"type":"object","properties":{
  #               "id":{"type":"string"},
  #               "mrn":{"type":"string"},
  #               "dob":{"type":"string","format":"date"},
  #               "name":{"type":"string"}
  #             }},
  #             "details":{"type":"object"}
  #           },
  #           "required": ["task","patient"]
  #         }
  #     - format: file
  #       contentTypes: [application/pdf, text/csv, application/json]
  #   outputs:
  #     - format: json 
  #       contentTypes: [application/json]
  #       schemaDefinition: |
  #         {
  #           "$schema": "https://json-schema.org/draft/2020-12/schema",
  #           "title": "CareCoordinationResponse",
  #           "type": "object",
  #           "properties": {
  #             "status": {"type":"string","enum":["success","failure","escalate"]},
  #             "summary": {"type":"string"},
  #             "actions": {
  #               "type":"array",
  #               "items":{
  #                 "type":"object",
  #                 "properties":{
  #                   "actionType":{"type":"string","enum":["fhirRead","fhirUpdate","scheduleAppointment","sendMessage","checkEligibility"]},
  #                   "parameters":{"type":"object"}
  #                 },
  #                 "required":["actionType","parameters"]
  #               }
  #             },
  #             "escalationReason":{"type":"string"}
  #           },
  #           "required": ["status","summary"]
  #         }
  #     - format: text 
  #       contentTypes: [text/markdown, text/plain]

  # Generic Agent Capabilities - Maps to different ADK-specific implementations
  behavior:
    # Reasoning and Planning Capabilities
    reasoning:
      enabled: true
      maxReasoningTokens: 1024
    determinism:
      seed: 42
    contextWindow:
      maxPromptTokens: 32000
      truncationStrategy: back
    # Response Generation
    responseGeneration:
      streaming: false                  # Enable real-time response streaming
      streamIntermediateSteps: false              
    responseFormat:
      type: json # need to be added 
  stateManagement:
    # Memory Configuration - Maps to different memory systems across ADKs
    memory:
      enabled: true # change the spec in github (remove type and add it as enable or dsiable )
      # Memory manager to use for this agent (implementation-specific)
      # Enable the agent to manage memories of the user autonomously
      table: agent_memories # need to add this in spec
      agenticMemory: false         # Maps to AgentOS: enable_agentic_memory
      # If True, the agent creates/updates user memories at the end of runs
      userMemories: false          # Maps to AgentOS: enable_user_memories
      # If True, the agent adds a reference to the user memories in the response
      addMemoriesToContext: null   # Maps to AgentOS: add_memories_to_context (null = auto-decide)
    # Session Management - Generic session handling
    session:
      enabled: true     
      table_name: agentname_session # need to add this               # Enable session state management  
        # Secrets and Configuration Management - Generic secrets handling
    secretsProvider:
      type: AzureKeyVault
      azureKeyVault:
        vaultName: kv-care-prod
        tenantId: <azure-tenant-id>
        useManagedIdentity: true   

  llmGateways: # enhance the gateway to use hcp cleint details- update accordingly in the spec
    - identity:
        urn: urn:llm:azure-openai:prod # how do we get this and do we really need this?
        uuid: 64ab0c83-1f2b-46b1-8b1a-2a9fb8b81b01 # how to get this and do we really need this?
        displayName: Azure OpenAI (Prod)
      endpoint: https://<your-aoai-endpoint>.openai.azure.com/ # hcp endpoint
      vendor: Azure   # Azure
      apiVersion: "2024-06-01" #remove this form here and move it under llm
      defaultModel: gpt-4o # remove this 
      models: ["gpt-4o", "gpt-4o-mini"] # nt needed in spec
      authentication:
        type: HcpIdentity # need to add the below identity types in the spec
        managedIdentity:
          clientId: <managed-identity-client-id>
          clientSecretRef:
            vaultName: <AZURE_KEY_VAULT_NAME>
            secretName: llmgw-client-secret
          scope: https://api.uhg.com/.default

  llm: 
    gatewayRef:
      urn: urn:llm:azure-openai:prod # is there any specific format? 
    model: gpt-4o
    apiVersion: "2024-06-01" #need to add this 
    projectId: 1234532344 # need to add this
    parameters:
      temperature: 0.2
      topP: 0.9 
      maxTokens: 1200
      stopSequences: [</END>]

  knowledgeBases:
    - identity:
        urn: urn:kb:azuresearch:clinical-guidelines
        uuid: 73c1b4bc-3b4e-4e8e-9a6f-4e0b8a2a0d11
      name: clinical-guidelines
      rag:
        chunking:
          chunkingType: enum [Fixed Size Chunking, Semantic Chunking, Recursive Chunking, Document Chunking, CSV Row Chunking, Markdown Chunking, Custom Chunking]
          chunkSize: 800
          chunkOverlap: 100
          separator: ---
          similarity_threshold: 0.5
          rows_per_chunk: 100
          skip_header: true
          clean_rows: true
          include_header_in_chunks: false
          max_chunk_size: 5000
          dedupe: true
        embedding:
          model: enum [AzureOpenAIEmbedder]
          endpoint: https://<your-aoai-endpoint>.openai.azure.com/
          apiVersion: "2024-06-01" 
          authentication:
           type: HcpIdentity # need to add the below identity types in the spec
           managedIdentity:
            clientId: <managed-identity-client-id>
            clientSecretRef:
              vaultName: <AZURE_KEY_VAULT_NAME>
              secretName: llmgw-client-secret
          scope: https://api.uhg.com/.default     
          dimension: 3072
        vectordatabase:
         type: enum [Pgvector]
         connectionurl: https://connection-url
         tableName: autogenerate based on input
         schema: default schema
         search_type: hybrid
        index:
          metric: cosine
          hnsw:
            m: 48
            efConstruction: 400
          hybrid: true
        retrieval:
          topK: 6
          mmr: true
          recencyBoost: true
          requireCitations: true
    

  # ---- MCP servers used by the tools below ----
  mcpServers:
    - identity:
        urn: urn:mcp:fhir:epic
        uuid: 9458b9d6-0a9a-4572-a3a2-19e3df405a10
        displayName: Epic FHIR Server
      url: https://fhir.example.org
      protocol: https
      authentication:
        type: OIDC
        oidc:
          issuer: https://login.microsoftonline.com/<tenant-id>/v2.0
          audience: api://ehr-fhir
          clientId: <app-client-id>
          clientSecretRef:
            keyName: EHR_OIDC_CLIENT_SECRET


  tools:
    - name: fhir-read
      description: Retrieve patient demographics and clinical resources (R4) by patient ID/MRN.
      mcp:
        serverRef:
          urn: urn:mcp:fhir:epic
        toolName: fhir.query
      timeoutMs: 15000
      retries: 2
      scopes: [ "ehr.read", "patient.demographics" ]

  a2aRegistries:
    - identity:
        urn: urn:a2a:registry:internal
        uuid: 0a07b9d2-ef66-47a2-8c01-5f9a1d255a77
        displayName: Internal A2A Registry
      url: https://agents.example.org/registry
      protocol: https
      authentication:
        clientId: <a2a-client-id>
        clientSecretRef:
          keyName: A2A_CLIENT_SECRET
        tokenUrl: https://login.example.org/oauth2/token
        scopes: [ "agents.read", "agents.write" ]

  a2a:
    card:
      protocolVersion: "1.0"
      name: Clinical Care Coordinator
      description: Coordinates care plans, benefits, scheduling, messaging, and referrals.
      version: "1.0.0"
      iconUrl: https://example.org/icons/clinical-care-coordinator.png
      documentationUrl: https://docs.example.org/agents/clinical-care-coordinator
      provider:
        organization: CareOrg Health
        url: https://www.careorg.example.org
      preferredInterface:
        url: https://agents.example.org/ccc
        transport: HTTP+JSON
      capabilities:
        streaming: true
        pushNotifications: true
        stateTransitionHistory: true
      defaultInputModes: ["text","json"]
      defaultOutputModes: ["json","text"]
      skills:
        - id: careplan-summarize
          name: Summarize Care Plan
          description: Produce a plain-language summary of a CarePlan for the patient portal.
          tags: ["careplan","summary","patient-facing"]
          examples: ["Summarize CarePlan/<id> for a 7th grade reading level."]
          inputModes: ["json","text"]
          outputModes: ["json","text"]
        - id: schedule-followup
          name: Schedule Follow-up
          description: Propose slots and book appointments based on clinician availability & care pathways.
          tags: ["scheduling","follow-up"]
          inputModes: ["json"]
          outputModes: ["json"]


  securityConfig:
    guardrails:
      input: {}
      output: {}
    evaluations:
      - name: phi-leakage-check
        metric: accuracy
        datasetRef: datasets/phi-redaction-e2e.jsonl
        schedule: "0 3 * * 1"   # Mondays

  security:
    rbac:
      roles: ["care-coordinator","ehr-reader","ehr-writer"]
      allowedCallers:
        - urn: urn:agent:care:triage-assistant
    dataPolicy:
      classification: PHI           # Public | Internal | Confidential | PHI
      redactPII: true
      retentionDays: 30
    egress:
      allowlist:
        - https://<your-aoai-endpoint>.openai.azure.com
        - https://fhir.example.org
        - https://scheduling.example.org
        - https://messaging.example.org
        - https://eligibility.example.org
        - https://<your-search>.search.windows.net
      mtls: false
      jwksUri: ""
    secrets:
      rotationDays: 90
      useManagedIdentity: true

  ops:
    # observability: remove these as by defualt we will enable this 
    #   logs_enabled: true
    # retention:
    #   telemetry_days: 30
    timeouts:
      defaultMs: 20000
    retries:
      max: 2
      backoffMs: 250
    rateLimit:
      rpm: 120
      rps: 5
    # resources: not needed this in agent spec
    #   cpu: "500m"
    #   memory: "1Gi"
    #   gpu: "0"

  evaluation:
    datasets:
      - datasets/careplan-groundtruth.jsonl
    metrics:
      - factuality
      - instruction_following
      - hallucination
    thresholds:
      factuality: 0.90
      instruction_following: 0.95
      hallucination: 0.05
    gatingPolicy: warn

  community:
    docsUrl: https://docs.example.org/agents/clinical-care-coordinator
    examplesUrl: https://docs.example.org/agents/clinical-care-coordinator/examples
    contributionGuideUrl: https://docs.example.org/contributing
    license: Apache-2.0
